version: '3.4'

services:
  web-server:
    build:
      context: .
      dockerfile: .docker/services/nginx/Dockerfile
      target: runtime
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/nginx/html

  app:
    build:
      context: .
      dockerfile: .docker/services/php/Dockerfile
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
    volumes:
      - .:/var/www/html

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  elasticsearch:
    driver: local
